// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edge-service-mgmt.proto

package eservicemgmt

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeployResp_MsgType int32

const (
	DeployResp_ERR DeployResp_MsgType = 0
	DeployResp_OK  DeployResp_MsgType = 1
)

var DeployResp_MsgType_name = map[int32]string{
	0: "ERR",
	1: "OK",
}

var DeployResp_MsgType_value = map[string]int32{
	"ERR": 0,
	"OK":  1,
}

func (x DeployResp_MsgType) String() string {
	return proto.EnumName(DeployResp_MsgType_name, int32(x))
}

func (DeployResp_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_959632b8e7dabf49, []int{1, 0}
}

type DeployReq struct {
	// The target application
	AppUUID string `protobuf:"bytes,1,opt,name=AppUUID,proto3" json:"AppUUID,omitempty"`
	// The universal unique ID assign to the service (the running application)
	ServUUID string `protobuf:"bytes,2,opt,name=ServUUID,proto3" json:"ServUUID,omitempty"`
	// Manifest for application deployment
	MajorManifest string `protobuf:"bytes,3,opt,name=MajorManifest,proto3" json:"MajorManifest,omitempty"`
	// Extra options for application startup
	MinorManifest        string   `protobuf:"bytes,4,opt,name=MinorManifest,proto3" json:"MinorManifest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployReq) Reset()         { *m = DeployReq{} }
func (m *DeployReq) String() string { return proto.CompactTextString(m) }
func (*DeployReq) ProtoMessage()    {}
func (*DeployReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_959632b8e7dabf49, []int{0}
}

func (m *DeployReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployReq.Unmarshal(m, b)
}
func (m *DeployReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployReq.Marshal(b, m, deterministic)
}
func (m *DeployReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployReq.Merge(m, src)
}
func (m *DeployReq) XXX_Size() int {
	return xxx_messageInfo_DeployReq.Size(m)
}
func (m *DeployReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeployReq proto.InternalMessageInfo

func (m *DeployReq) GetAppUUID() string {
	if m != nil {
		return m.AppUUID
	}
	return ""
}

func (m *DeployReq) GetServUUID() string {
	if m != nil {
		return m.ServUUID
	}
	return ""
}

func (m *DeployReq) GetMajorManifest() string {
	if m != nil {
		return m.MajorManifest
	}
	return ""
}

func (m *DeployReq) GetMinorManifest() string {
	if m != nil {
		return m.MinorManifest
	}
	return ""
}

type DeployResp struct {
	T DeployResp_MsgType `protobuf:"varint,1,opt,name=T,proto3,enum=eservicemgmt.DeployResp_MsgType" json:"T,omitempty"`
	// --- ERR ---
	ErrStr               string   `protobuf:"bytes,2,opt,name=ErrStr,proto3" json:"ErrStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResp) Reset()         { *m = DeployResp{} }
func (m *DeployResp) String() string { return proto.CompactTextString(m) }
func (*DeployResp) ProtoMessage()    {}
func (*DeployResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_959632b8e7dabf49, []int{1}
}

func (m *DeployResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResp.Unmarshal(m, b)
}
func (m *DeployResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResp.Marshal(b, m, deterministic)
}
func (m *DeployResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResp.Merge(m, src)
}
func (m *DeployResp) XXX_Size() int {
	return xxx_messageInfo_DeployResp.Size(m)
}
func (m *DeployResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResp proto.InternalMessageInfo

func (m *DeployResp) GetT() DeployResp_MsgType {
	if m != nil {
		return m.T
	}
	return DeployResp_ERR
}

func (m *DeployResp) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type DestroyReq struct {
	// The target service to destroy
	ServUUID             string   `protobuf:"bytes,1,opt,name=ServUUID,proto3" json:"ServUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyReq) Reset()         { *m = DestroyReq{} }
func (m *DestroyReq) String() string { return proto.CompactTextString(m) }
func (*DestroyReq) ProtoMessage()    {}
func (*DestroyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_959632b8e7dabf49, []int{2}
}

func (m *DestroyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyReq.Unmarshal(m, b)
}
func (m *DestroyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyReq.Marshal(b, m, deterministic)
}
func (m *DestroyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyReq.Merge(m, src)
}
func (m *DestroyReq) XXX_Size() int {
	return xxx_messageInfo_DestroyReq.Size(m)
}
func (m *DestroyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyReq.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyReq proto.InternalMessageInfo

func (m *DestroyReq) GetServUUID() string {
	if m != nil {
		return m.ServUUID
	}
	return ""
}

type DiscoverReq struct {
	// The target application
	AppUUID              string   `protobuf:"bytes,1,opt,name=AppUUID,proto3" json:"AppUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverReq) Reset()         { *m = DiscoverReq{} }
func (m *DiscoverReq) String() string { return proto.CompactTextString(m) }
func (*DiscoverReq) ProtoMessage()    {}
func (*DiscoverReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_959632b8e7dabf49, []int{3}
}

func (m *DiscoverReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverReq.Unmarshal(m, b)
}
func (m *DiscoverReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverReq.Marshal(b, m, deterministic)
}
func (m *DiscoverReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverReq.Merge(m, src)
}
func (m *DiscoverReq) XXX_Size() int {
	return xxx_messageInfo_DiscoverReq.Size(m)
}
func (m *DiscoverReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverReq.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverReq proto.InternalMessageInfo

func (m *DiscoverReq) GetAppUUID() string {
	if m != nil {
		return m.AppUUID
	}
	return ""
}

type DiscoverResp struct {
	// Manifest for invoking the services
	Manifest             string   `protobuf:"bytes,1,opt,name=Manifest,proto3" json:"Manifest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverResp) Reset()         { *m = DiscoverResp{} }
func (m *DiscoverResp) String() string { return proto.CompactTextString(m) }
func (*DiscoverResp) ProtoMessage()    {}
func (*DiscoverResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_959632b8e7dabf49, []int{4}
}

func (m *DiscoverResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverResp.Unmarshal(m, b)
}
func (m *DiscoverResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverResp.Marshal(b, m, deterministic)
}
func (m *DiscoverResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverResp.Merge(m, src)
}
func (m *DiscoverResp) XXX_Size() int {
	return xxx_messageInfo_DiscoverResp.Size(m)
}
func (m *DiscoverResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverResp.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverResp proto.InternalMessageInfo

func (m *DiscoverResp) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func init() {
	proto.RegisterEnum("eservicemgmt.DeployResp_MsgType", DeployResp_MsgType_name, DeployResp_MsgType_value)
	proto.RegisterType((*DeployReq)(nil), "eservicemgmt.DeployReq")
	proto.RegisterType((*DeployResp)(nil), "eservicemgmt.DeployResp")
	proto.RegisterType((*DestroyReq)(nil), "eservicemgmt.DestroyReq")
	proto.RegisterType((*DiscoverReq)(nil), "eservicemgmt.DiscoverReq")
	proto.RegisterType((*DiscoverResp)(nil), "eservicemgmt.DiscoverResp")
}

func init() {
	proto.RegisterFile("edge-service-mgmt.proto", fileDescriptor_959632b8e7dabf49)
}

var fileDescriptor_959632b8e7dabf49 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0x87, 0x59, 0x30, 0x2d, 0x8c, 0xa8, 0x64, 0x0e, 0x52, 0xf7, 0x44, 0x36, 0x26, 0x12, 0x13,
	0x7a, 0xc0, 0xb3, 0x07, 0x23, 0x3d, 0x18, 0xd3, 0x98, 0x14, 0x78, 0x00, 0xfe, 0xac, 0x4d, 0x0d,
	0xa5, 0xcb, 0xee, 0x86, 0x84, 0x87, 0xf0, 0xad, 0x7c, 0x30, 0xd3, 0xed, 0x16, 0x8a, 0x8a, 0xc7,
	0x99, 0xf9, 0xb2, 0xf3, 0xfb, 0x26, 0x0b, 0x5d, 0xbe, 0x8c, 0xf9, 0x40, 0x71, 0xb9, 0x4d, 0x16,
	0x7c, 0x90, 0xc6, 0xa9, 0xf6, 0x85, 0xcc, 0x74, 0x86, 0x6d, 0x6e, 0x9b, 0x79, 0x8f, 0xb6, 0xe3,
	0x55, 0x36, 0x9f, 0xad, 0x8a, 0x19, 0xfb, 0x24, 0xd0, 0x1a, 0x71, 0xb1, 0xca, 0x76, 0x11, 0xdf,
	0xa0, 0x07, 0xee, 0x93, 0x10, 0xd3, 0xe9, 0xcb, 0xc8, 0x23, 0x3d, 0xd2, 0x6f, 0x45, 0x65, 0x89,
	0x14, 0x9a, 0x63, 0x2e, 0xb7, 0x66, 0x54, 0x37, 0xa3, 0x7d, 0x8d, 0xb7, 0x70, 0x11, 0xce, 0x3e,
	0x32, 0x19, 0xce, 0xd6, 0xc9, 0x3b, 0x57, 0xda, 0x6b, 0x18, 0xe0, 0xb8, 0x69, 0xa8, 0x64, 0x5d,
	0xa1, 0xce, 0x2c, 0x55, 0x6d, 0x32, 0x01, 0x50, 0xc6, 0x51, 0x02, 0x7d, 0x20, 0x13, 0x93, 0xe4,
	0x72, 0xd8, 0xf3, 0xab, 0x16, 0xfe, 0x01, 0xf2, 0x43, 0x15, 0x4f, 0x76, 0x82, 0x47, 0x64, 0x82,
	0xd7, 0xe0, 0x04, 0x52, 0x8e, 0xb5, 0xb4, 0x19, 0x6d, 0xc5, 0x28, 0xb8, 0x96, 0x42, 0x17, 0x1a,
	0x41, 0x14, 0x75, 0x6a, 0xe8, 0x40, 0xfd, 0xed, 0xb5, 0x43, 0x58, 0x3f, 0xdf, 0xa8, 0xb4, 0x2c,
	0x2e, 0x50, 0xf5, 0x24, 0xc7, 0x9e, 0xec, 0x0e, 0xce, 0x47, 0x89, 0x5a, 0x64, 0x5b, 0x2e, 0xff,
	0x3d, 0x16, 0xbb, 0x87, 0xf6, 0x01, 0x54, 0x22, 0x7f, 0x74, 0x6f, 0x6d, 0x1f, 0x2d, 0xeb, 0xe1,
	0x17, 0x81, 0xab, 0x60, 0x19, 0xf3, 0x71, 0x21, 0x17, 0xc6, 0xa9, 0xc6, 0x47, 0x70, 0x0a, 0x3f,
	0xec, 0xfe, 0x6d, 0xbd, 0xa1, 0xde, 0xa9, 0x73, 0xb0, 0x1a, 0x0e, 0xc0, 0xb5, 0x46, 0xf8, 0x0b,
	0x2b, 0x45, 0xa9, 0xe3, 0x07, 0xa9, 0xd0, 0x3b, 0x56, 0xc3, 0x67, 0x68, 0x96, 0x69, 0xf1, 0xe6,
	0x07, 0x7f, 0xd0, 0xa5, 0xf4, 0xd4, 0x28, 0xdf, 0x39, 0x77, 0xcc, 0x77, 0x7a, 0xf8, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x70, 0xff, 0x61, 0x80, 0x85, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

type Empty struct{}

// EdgeServiceMgmtClient is the client API for EdgeServiceMgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EdgeServiceMgmtClient interface {
	// Deploy starts an application on the edge node.
	Deploy(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (*DeployResp, error)
	// Destroy stops a service running on the edge node.
	Destroy(ctx context.Context, in *DestroyReq, opts ...grpc.CallOption) (*Empty, error)
	// Discover returns the running service of an application.
	Discover(ctx context.Context, in *DiscoverReq, opts ...grpc.CallOption) (*DiscoverResp, error)
}

type edgeServiceMgmtClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeServiceMgmtClient(cc grpc.ClientConnInterface) EdgeServiceMgmtClient {
	return &edgeServiceMgmtClient{cc}
}

func (c *edgeServiceMgmtClient) Deploy(ctx context.Context, in *DeployReq, opts ...grpc.CallOption) (*DeployResp, error) {
	out := new(DeployResp)
	err := c.cc.Invoke(ctx, "/eservicemgmt.EdgeServiceMgmt/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceMgmtClient) Destroy(ctx context.Context, in *DestroyReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/eservicemgmt.EdgeServiceMgmt/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceMgmtClient) Discover(ctx context.Context, in *DiscoverReq, opts ...grpc.CallOption) (*DiscoverResp, error) {
	out := new(DiscoverResp)
	err := c.cc.Invoke(ctx, "/eservicemgmt.EdgeServiceMgmt/Discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeServiceMgmtServer is the server API for EdgeServiceMgmt service.
type EdgeServiceMgmtServer interface {
	// Deploy starts an application on the edge node.
	Deploy(context.Context, *DeployReq) (*DeployResp, error)
	// Destroy stops a service running on the edge node.
	Destroy(context.Context, *DestroyReq) (*Empty, error)
	// Discover returns the running service of an application.
	Discover(context.Context, *DiscoverReq) (*DiscoverResp, error)
}

// UnimplementedEdgeServiceMgmtServer can be embedded to have forward compatible implementations.
type UnimplementedEdgeServiceMgmtServer struct {
}

func (*UnimplementedEdgeServiceMgmtServer) Deploy(ctx context.Context, req *DeployReq) (*DeployResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (*UnimplementedEdgeServiceMgmtServer) Destroy(ctx context.Context, req *DestroyReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (*UnimplementedEdgeServiceMgmtServer) Discover(ctx context.Context, req *DiscoverReq) (*DiscoverResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}

func RegisterEdgeServiceMgmtServer(s *grpc.Server, srv EdgeServiceMgmtServer) {
	s.RegisterService(&_EdgeServiceMgmt_serviceDesc, srv)
}

func _EdgeServiceMgmt_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceMgmtServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eservicemgmt.EdgeServiceMgmt/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceMgmtServer).Deploy(ctx, req.(*DeployReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeServiceMgmt_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceMgmtServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eservicemgmt.EdgeServiceMgmt/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceMgmtServer).Destroy(ctx, req.(*DestroyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeServiceMgmt_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceMgmtServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eservicemgmt.EdgeServiceMgmt/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceMgmtServer).Discover(ctx, req.(*DiscoverReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EdgeServiceMgmt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eservicemgmt.EdgeServiceMgmt",
	HandlerType: (*EdgeServiceMgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _EdgeServiceMgmt_Deploy_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _EdgeServiceMgmt_Destroy_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _EdgeServiceMgmt_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edge-service-mgmt.proto",
}
