// Code generated by protoc-gen-go. DO NOT EDIT.
// source: global.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ArchOS defines a list of architecture-OS specifications.
type ArchOS int32

const (
	ArchOS_AMD64__LINUX       ArchOS = 0
	ArchOS_ARM64__LINUX       ArchOS = 1
	ArchOS_ANY__IPADOS_SAFARI ArchOS = 2
)

var ArchOS_name = map[int32]string{
	0: "AMD64__LINUX",
	1: "ARM64__LINUX",
	2: "ANY__IPADOS_SAFARI",
}

var ArchOS_value = map[string]int32{
	"AMD64__LINUX":       0,
	"ARM64__LINUX":       1,
	"ANY__IPADOS_SAFARI": 2,
}

func (x ArchOS) String() string {
	return proto.EnumName(ArchOS_name, int32(x))
}

func (ArchOS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.ArchOS", ArchOS_name, ArchOS_value)
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

func init() {
	proto.RegisterFile("global.proto", fileDescriptor_4baa8fc7dedf329e)
}

var fileDescriptor_4baa8fc7dedf329e = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0xc9, 0x4f,
	0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x62, 0xe7, 0x62,
	0x75, 0xcd, 0x2d, 0x28, 0xa9, 0xd4, 0x72, 0xe1, 0x62, 0x73, 0x2c, 0x4a, 0xce, 0xf0, 0x0f, 0x16,
	0x12, 0xe0, 0xe2, 0x71, 0xf4, 0x75, 0x31, 0x33, 0x89, 0x8f, 0xf7, 0xf1, 0xf4, 0x0b, 0x8d, 0x10,
	0x60, 0x00, 0x8b, 0x04, 0xf9, 0x22, 0x44, 0x18, 0x85, 0xc4, 0xb8, 0x84, 0x1c, 0xfd, 0x22, 0xe3,
	0xe3, 0x3d, 0x03, 0x1c, 0x5d, 0xfc, 0x83, 0xe3, 0x83, 0x1d, 0xdd, 0x1c, 0x83, 0x3c, 0x05, 0x98,
	0x92, 0xd8, 0xc0, 0x26, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x57, 0x04, 0x6e, 0x2b, 0x69,
	0x00, 0x00, 0x00,
}
